### ISSUE TITLE
Is there a way to tweak the background color?

### ISSUE THREAD

**Issue by corky158e** [LanikSJ/slack-dark-mode#103]
<img width="1053" alt="Screen Shot 2019-07-25 at 2 43 37 PM" src="https://user-images.githubusercontent.com/3800838/61910859-a11b1e00-aeea-11e9-96e3-7447412c67b5.png">
After running the script, I did indeed get a dark mode theme, but as you can see the chat area and the user list on the right have the same background which is less than ideal.

**Comment by LanikSJ** [comment]
It was something that was requested in #93 if you want to undo those changes you'll get the sidebar as different color.

**Comment by mikepenz** [comment]
@corky158e with the latest changes it is now easy to set a custom color value if you like.

Just set: https://github.com/LanikSJ/slack-dark-mode/blob/master/dark-theme.css#L6 to any color value you prefer :)

**Comment by krazyito65** [comment]
This worked for me inbetween the channel list and the messages, but what about the other direction? in between the main channel msgs and thread view.

**Comment by mikepenz** [comment]
@krazyito65 I will have a look to theme the thread view. good point

**Comment by krazyito65** [comment]
I need to personally make a script to update these CSS side bars each time I pull updates from github.. haha.  I don't expect you guys to do that though if think this is the correct aesthetic for your theme.

**Comment by mikepenz** [comment]
@krazyito65 I am actually waiting for some feedback of the maintainer here: https://github.com/LanikSJ/slack-dark-mode/pull/119#discussion_r310749037 first. 

Let's see :) Definitely want to follow the vision of the maintainer and don't add things which are not expected or asked for

**Comment by krazyito65** [comment]
BTW: While testing my current PR for Windows, it doesn't seem that this styling for threads on #123 was working..

`--thread-bg-color`.  It seems to work fine on my Linux machine though..

**Comment by krazyito65** [comment]
This issue should be resolved now via https://github.com/LanikSJ/slack-dark-mode/pull/126

But might need slight updates in the future depending what needs to be tweaked, but at least users can add their own small changes easily without it being overwritten each time the repo is updated.

**Comment by mikepenz** [comment]
#126 is great :D saves me time too :D

**Comment by krazyito65** [comment]
Well, technically this is already solved.
