### ISSUE TITLE
Emoji & tagging people have a white background. Anyway to get that to be dark? 

### ISSUE THREAD

**Issue by mprice0064** [LanikSJ/slack-dark-mode#104]
**Is your feature request related to a problem? Please describe.**
When typing an Emoji (start typing a :) & when tagging people (start typing @) and the box that opens has a white background. Anyway to get that to be dark? 

**Describe the solution you'd like**
Emoji & tagging people have a dark background. 
![Screen Shot 2019-07-26 at 10 15 02 AM](https://user-images.githubusercontent.com/7748090/61958049-974af680-af8e-11e9-8afe-e0cda3708c3c.png)

**Comment by LanikSJ** [comment]
I'm not able to reproduce this I see dark background for mentions.  Make sure you install latest version of Slack and run `slack-dark-mode.sh -u` again.

**Comment by mprice0064** [comment]
A re-install didn't fix it. I quit out of slack, then ran source slack-dark-mode.sh -u then restarted slack and that fixed it. Thanks for your help! Loving the dark theme!!
