### ISSUE TITLE
White background in the outage page.

### ISSUE THREAD

**Issue by nicoyuste** [LanikSJ/slack-dark-mode#107]
**Describe the bug**
If Slack is experiencing an outage it tells you in the app. Unlikely, that is not really working when you have this applied.

**To Reproduce**
1\. Wait for Slack to have an outage. 🤷‍♂ 

**Expected behavior**
Background should be black.

**Screenshots**
<img width="1453" alt="Captura de pantalla 2019-07-29 a las 17 27 33" src="https://user-images.githubusercontent.com/5048526/62060948-6f75c000-b226-11e9-98ee-28ef035248d4.png">

**Desktop (please complete the following information):**

-   OS: Mojave 10.14.6
-   Slack Version: 4.0.0

**Comment by LanikSJ** [comment]
Until I can see that menu again it will be nearly impossible for me to fix this unfortunately. 😔
