### ISSUE TITLE
Script has no effect on Slack 4.0.1

### ISSUE THREAD

**Issue by kschar** [LanikSJ/slack-dark-mode#108]
Installed Brew and Node (from within Brew), edited bootSonic to never, and ran 'sudo ./slack-dark-mode.sh -u' and it runs to completion with no errors but when I open Slack it still has white conversations :( (Running Slack 4.0.1 on MacOS 10.14.6) Thanks for any pointers.

**Comment by kschar** [comment]
Installed Brew and Node (from within Brew), edited bootSonic to never, and ran 'sudo ./slack-dark-mode.sh -u' and it runs to completion with no errors but when I open Slack it still has white conversations :( (Running Slack 4.0.1 on MacOS 10.14.6) Thanks for any pointers.

**Comment by cwchung95** [comment]
I have the same problem

**Comment by LanikSJ** [comment]
You ran it with a `-u` switch which updates and doesn't add anything.  Remove `-u` and run the `./slack-dark-mode.sh`

**Comment by kschar** [comment]
Doh!   Thanks @LanikSJ

**Comment by dairennlombard** [comment]
I ran it without the `-u` switch and as of 8/16/2019 on my version 4.0.1 Slack install, it does not work (this is macOS 10.14.5).
