### ISSUE TITLE
Revert back to light mode

### ISSUE THREAD

**Issue by bevankoopman** [LanikSJ/slack-dark-mode#111]
Include functionality to revert back to light mode.

**Comment by LanikSJ** [comment]
I think it's possible I'll try some stuff as time permits.  It won't be clean though.  The cleanest method is to reinstall the app and since there's at least 3 different ways to do that it can get quite complicated.

**Comment by krazyito65** [comment]
I'm not 100% savvy on how all the js components work, but could you just add an if statement and a boolean to allow the event listener code to go through?

Then all you would have to do is just set a true/false value for a variable.

**Comment by krazyito65** [comment]
Another option would be.. From a fresh install (need to detect if dark mode has been enabled in the past before you can do this) is copy the original interop file somewhere and name it as "original" so we can just replace it.

**Comment by krazyito65** [comment]
I think ill work on this next, if i have time over the next week.

**Comment by krazyito65** [comment]
Actually... on windows and ubuntu simply deleting/renaming the css file will revert back to light mode.

**Comment by krazyito65** [comment]
@LanikSJ Can you test my branch on Mac? https://github.com/krazyito65/slack-dark-mode/tree/light-mode

**Comment by LanikSJ** [comment]
Just a few suggestions.  Otherwise I know that's going to work since I've tried it.

Your `rm` command should have a `-f` just in case there's a prompt or something else.

**Comment by krazyito65** [comment]
good point

**Comment by LanikSJ** [comment]
I usually do an `exit 0` in my scripts when I want no more code to be processed.  But I think that's the same thing.

**Comment by krazyito65** [comment]
Yea it is, its default 0 when not specified.

Can you run it once on your mac to just to be sure now?

**Comment by LanikSJ** [comment]
```bash
→ ./slack-dark-mode.sh --light
./slack-dark-mode.sh: line 16: syntax error near unexpected token `)'
./slack-dark-mode.sh: line 16: `        *) echo "Option doesn't exist"; exit 1 ;;'
```
There also needs to be an option to run and install / modify everything.  Right now it just fails.

Line 15 is missing `;;` then everything works as intended.

**Comment by krazyito65** [comment]
>.> duh my bad.  I have to uninstall my slack and reinstall by base to test...

**Comment by krazyito65** [comment]
done

**Comment by krazyito65** [comment]
also the flag is `-light` do you want me to add `--light` or `-l` ?

**Comment by LanikSJ** [comment]
>There also needs to be an option to run and install / modify everything. Right now it just fails.

We need to somehow deal with people installing Dark Mode for first time.

> also the flag is `-light` do you want me to add `--light` or `-l` ?

I think we could support both `-l` and `--light`.  Just to make it easier to understand that we don't mean `-l` as in list.  😄

**Comment by krazyito65** [comment]
> We need to somehow deal with people installing Dark Mode for first time.

?? Seems to work for me?  I literally just uninstalled slack and did it.  I think it was because I took out `UPDATE_ONLY="false"`

**Comment by LanikSJ** [comment]
I'm sure it's fine let me try that out again.

**Comment by krazyito65** [comment]
LOL I LEFT AN EXIT from testing

**Comment by LanikSJ** [comment]
Okay I was just wondering why the script just exists. 😁

**Comment by krazyito65** [comment]
Yea, I was testing the case statement making sure I did the parameters right, and I forgot to remove that.

**Comment by krazyito65** [comment]
I'll fix code coverage.

**Comment by LanikSJ** [comment]
One thing to keep in mind about Code Coverage that I've found if Travis isn't running the code it's going to flag it for no coverage.  Putting the if statements in a single command would get around that problem.  That was me and hours and hours of fighting with CodeCov. 😆

**Comment by krazyito65** [comment]
yea, but its the last thing i think about atm (which is bad, but meh, not use to it haha) I just added the travis to run codecov again for the script with both not light and light, and it should work from what i remember doing last time... we'll see

**Comment by LanikSJ** [comment]
I do the same thing.  Amazingly great minds think alike.

**Comment by krazyito65** [comment]
I'm waiting for it to epicly fail becasue it over wrote the original report so it becomes 98% less covered.

**Comment by krazyito65** [comment]
Nice, it worked like i expected and made 2 reports.

**Comment by krazyito65** [comment]
I think thats what happened... im gonna try putting it in a new folder.

**Comment by krazyito65** [comment]
![image](https://user-images.githubusercontent.com/479738/63130112-02309180-bf7f-11e9-9bcd-da473fb06533.png)


.... 
*) echo "Option doesn't exist"; exit 1 ;;

but won't be covered otherwise.........

**Comment by LanikSJ** [comment]
I don't really care if that line isn't covered.

**Comment by krazyito65** [comment]
Nah I fixed it!

**Comment by LanikSJ** [comment]
I take your word for it.  I'll wait for Travis CodeCov do it's business.

**Comment by krazyito65** [comment]
I do devops for a living doing basically this, but its just kinda annoying when its in the cloud and i have to wait for the entire thing to start over.

**Comment by krazyito65** [comment]
Take that codecov.

**Comment by LanikSJ** [comment]
> I do devops for a living doing basically this, but its just kinda annoying when its in the cloud and i have to wait for the entire thing to start over.

Another thing we have in common. 😁 

I've spent hours swearing at CodeCov, so I feel your pain.

**Comment by LanikSJ** [comment]
Alright lets :shipit:

**Comment by krazyito65** [comment]
@bevankoopman TL;DR You can now revert to light mode :)
