### ISSUE TITLE
Color bug in name of the author

### ISSUE THREAD

**Issue by renanzapelini** [LanikSJ/slack-dark-mode#114]
Sorry for my english, brazilian typing hehe.

**Describe the bug**
When you share(or mentions) a message, the name of the author of the message is displayed with font in dark color), and with dark  background too is not easy to see the name of the author.

**To Reproduce**
1\. Send a message
2\. Mentions this message (Share)
3\. The author of the mentioned message is displayed, but it's hard to see his name

**Expected behavior**
Is expected that the name of the author of the messages will be easier to see.

**Screenshots**
![issue dark slack](https://user-images.githubusercontent.com/38230449/62240482-7a0e9180-b3ad-11e9-9ae0-7402c388282d.png)

**Desktop (please complete the following information):**

-   OS: (e.g. macOS) -  Ubuntu 19.04
-   Slack Version (e.g. 3.0) - Produção 4.0.0 64-bit

**Comment by LanikSJ** [comment]
I'm not able to reproduce this.  I know 4.0.1 is available for macOS if it's available for Linux please test that and see what happens.
