### ISSUE TITLE
Pins CSS not correctly styled.

### ISSUE THREAD

**Issue by krazyito65** [LanikSJ/slack-dark-mode#118]
**Describe the bug**
Pins styling is not correct.

**To Reproduce**
Open 'pins' in any channel

**Screenshots**
![image](https://user-images.githubusercontent.com/479738/62482069-c70db180-b779-11e9-92f2-2b92665c6928.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 19.04
-   Slack Version: 4.0

**Comment by LanikSJ** [comment]
I was able to reproduce this.  Thank you for the bug report a fix should be in shortly.

**Comment by krazyito65** [comment]
I found another one while you're at it, do you want me to make a new issue for it?

When you try to start a new direct msg:
![image](https://user-images.githubusercontent.com/479738/62487889-997c3480-b788-11e9-8604-ae7663f83a9c.png)

**Comment by LanikSJ** [comment]
Yeah I noticed that one too. Let's open a new issue.

Keep the bug reports coming. :+1: 🙂
