### ISSUE TITLE
User profile preview not styling

### ISSUE THREAD

**Issue by krazyito65** [LanikSJ/slack-dark-mode#121]
**To Reproduce**
In any chat channel, click on someone's username and view a preview of their profile.

*minor*
Also, when you open their profile on the side bar the `...` to the right of 'Edit Profile' is hard to see.

**Screenshots**
![image](https://user-images.githubusercontent.com/479738/62488340-ac433900-b789-11e9-9f3b-34507e7ffd0c.png)
![image](https://user-images.githubusercontent.com/479738/62488411-df85c800-b789-11e9-9d44-88a82b8bda02.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 19.04
-   Slack Version: 4.0

**Comment by krazyito65** [comment]
Also noticed the description text for each of these are not colored correctly and are hard to see: 

![image](https://user-images.githubusercontent.com/479738/62490192-57ee8800-b78e-11e9-914d-0a42bfff273c.png)

**Comment by LanikSJ** [comment]
If you could raise another issue for the button colors I'll have to find time to address it.  This isn't the only place I've seen them.

**Comment by krazyito65** [comment]
Will do. That was the only place I noticed perosonally. I'll make the issue
while I'm at work tomorrow.
