### ISSUE TITLE
Minor Profiling styling issues

### ISSUE THREAD

**Issue by krazyito65** [LanikSJ/slack-dark-mode#124]
**Describe the bug**
Here are a couple of minor profile styling issues I found

**To Reproduce**
Click on someones name in chat, to open the preview
mouse over their name.
![image](https://user-images.githubusercontent.com/479738/62549136-95eeb900-b82d-11e9-9fc7-390ef0886f94.png)

Then open their profile by clicking their name, and look at the `...` on the right of the edit profile button
![image](https://user-images.githubusercontent.com/479738/62549197-ad2da680-b82d-11e9-911f-0ade3b4d2a4a.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 19.02
-   Slack Version: 4.0

**Comment by krazyito65** [comment]
![image](https://user-images.githubusercontent.com/479738/62582315-9b6df280-b871-11e9-8401-0a88147e7aa3.png)

![image](https://user-images.githubusercontent.com/479738/62582323-9f9a1000-b871-11e9-826a-bfce9594b612.png)


Looks good.

**Comment by LanikSJ** [comment]
Since #130 is merged I'm closing this.
