### ISSUE TITLE
Labels unreadable in create channel screen

### ISSUE THREAD

**Issue by mrbruins** [LanikSJ/slack-dark-mode#133]
**Describe the bug**
Text of the labels in the create channel screen is unreadable because they are styled in black.

**To Reproduce**
1\. Click on the create channel button

**Screenshots**
![image](https://user-images.githubusercontent.com/1969831/62701709-4521c080-b9e5-11e9-9a39-c69fb2f0c1ee.png)

**Desktop (please complete the following information):**

-   OS: macOS)
-   Slack Version 4.0.1

**Comment by krazyito65** [comment]
Seems to also be affected in 'browse' channels
![image](https://user-images.githubusercontent.com/479738/62715015-404d1480-b9c5-11e9-9258-daf901df4f35.png)

**Comment by mikepenz** [comment]
@krazyito65 https://github.com/LanikSJ/slack-dark-mode/pull/136

**Comment by krazyito65** [comment]
Everything checks out on Linux.
