### ISSUE TITLE
Flipping bootsonic to "never" to make this work, reverts back to "once" when computer is restarted.

### ISSUE THREAD

**Issue by krstrong** [LanikSJ/slack-dark-mode#137]
Whenever I restart my computer the local-settings.json file reverts the bootsonic from "never" back to "once", which breaks the dark mode theme. As soon as I update it to "never" and then restart slack, the dark mode theme begins working again.

**Comment by krazyito65** [comment]
What OS are you using?

**Comment by LanikSJ** [comment]
Where was Slack installed from Apple Store or Directly downloaded?

**Comment by krazyito65** [comment]
> Where was Slack installed from Apple Store or Directly downloaded?

oh is this a Mac specific thing?

**Comment by krstrong** [comment]
@krazyito65 Yes I'm on a Mac and it's 10.14.6. 

@LanikSJ I can't remember where I initially downloaded it from, but it updates via the app store. So I'm guessing the app store was the original location...

**Comment by LanikSJ** [comment]
@krstrong I'm not able to reproduce that from the App Store version.

@krazyito65 Yes this is a Mac only thing.

**Comment by krstrong** [comment]
Okay, I'll try an uninstall/reinstall

**Comment by krstrong** [comment]
After uninstall reinstall this issue still occurs. I did make a point to uninstall all the system files related to slack and fully reinstall.

**Comment by krstrong** [comment]
@LanikSJ

**Comment by krazyito65** [comment]
I'm not 100% sure how Macs hand crontabs, but in the linux version I did i just ran `crontab -e` and added `@reboot <make changes`  That should at least fix that on reboot.  If that works, we could incorporate that into the script.

**Comment by krazyito65** [comment]
@krstrong could you add this to your crontab? (`sudo crontab -e`)

```
@reboot sed -i 's/"bootSonic":"once"/"bootSonic":"never"/g' "$HOME/Library/Application\ Support/Slack/local-settings.json"
```

```
@reboot sudo sed -i 's/"bootSonic":"once"/"bootSonic":"never"/g' "$HOME/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json"
```

**Comment by LanikSJ** [comment]
@krstrong should be fixed in https://github.com/LanikSJ/slack-dark-mode/pull/161
