### ISSUE TITLE
How do I make this work on Windows?

### ISSUE THREAD

**Issue by KTsarlz** [LanikSJ/slack-dark-mode#138]
I tried to use command prompt and git bash but I am getting **bash: .slack-dark-mode.ps1: command not found** in git bash and when I do the same in command prompt it opens the file in notepad. 

Anything I'm missing?

**Comment by krazyito65** [comment]
You have to use powershell in admin mode

**Comment by LanikSJ** [comment]
Yes we'll need to update the docs at some point to reflect this.
