### ISSUE TITLE
Light background color on names in Direct Message search list

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#147]
**Describe the bug**
When you search a new to send a new Direct Message, and then mouse over a list entry, the backgorund color is still light.

**To Reproduce**
1\. Go to 'Direct Message (+)' to start a new DM
2\. Type in a name of someone to message
3\. Mouse over any list entries and observe the incorrect color

**Expected behavior**
It should be a dark background color

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/63041120-b43b6100-be8c-11e9-8b6f-d649d5fcc3b7.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.0.1

**Additional context**
N/A

**Comment by robmonte** [comment]
I was hoping that the drop-down box change would fix this too as maybe they were the same component but it hasn't. Issue still occurring on Slack 4.0.2 and the newest script update.

**Comment by Zweih** [comment]
@robmonte I have a fix for this and will submit a PR shortly.
