### ISSUE TITLE
Receiving an error when running the command on windows

### ISSUE THREAD

**Issue by KTsarlz** [LanikSJ/slack-dark-mode#150]
This is the error: **Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.**

But this is what the whole error is:
`Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive. At C:\Users\kgonzales\Documents\slack-dark-mode\slack-dark-mode.ps1:46 char:1
+ Invoke-WebRequest -UseBasicParsing -Method GET -Uri $CSSUrl | Select- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

Although in unpacks and installs just fine, upon launching Slack it is still on light mode. 
![Screenshot_48](https://user-images.githubusercontent.com/9140507/63108390-50628680-bfb9-11e9-9653-d53e2519a12c.png)

EDIT: It seems the code doesn't format well, the whole message is seen in the screenshot

**Comment by krazyito65** [comment]
are you savvy enough to try this?
https://stackoverflow.com/a/15841856

**Comment by krazyito65** [comment]
Are you in Admin mode?  Not sure if i can tell from the screenshot either

**Comment by krazyito65** [comment]
To be honest, I want to fix this anyway so it's actually pulling from the local repo instead of the web..  Not sure what the original author was thinking

**Comment by krazyito65** [comment]
Here do this:

Replace like 47 (`Invoke-WebRequest`)
with this: 
`cat ./dark-theme.css | Set-Content -Path $themeFile # add the theme from the repo`

**Comment by krazyito65** [comment]
@KTsarlz Let me know if the update fixes it for you.

**Comment by KTsarlz** [comment]
@krazyito65 Thank you for the quick response!  And sorry for the late reply. I'm still at work and I just pulled the lastest from the repo and did the command again and now it works! Thanks a lot!

**Comment by krazyito65** [comment]
Yea I'm at work too, but I'm not so busy ;)
