### ISSUE TITLE
Manual Steps

### ISSUE THREAD

**Issue by kakins** [LanikSJ/slack-dark-mode#154]
Any chance for getting an outline to perform these steps manually instead of executing a script?  For instance, if some work organizations don't grant admin powershell execution rights then the script method won't work.

**Comment by krazyito65** [comment]
Pretty sure you're going to need the admin rights anyway to be able to open the archive.  

Regardless, you can always go through the script to try to figure out how to do it manually.


Essentially, you extract the asar archive (using npx) and then add a new ssb-interop file like we use to do the old way, but you have it point to the location of our custom CSS.  Then you simply pack up the asar and it should work.

**Comment by tmack0** [comment]
Its important to set bootSonic to never in the json files. If that doesn't change, it will not load the other css.

**Comment by krazyito65** [comment]
I think bootSonic is for Mac only, he is using windows.

**Comment by LanikSJ** [comment]
You can execute all the steps in the script manually if you like.  That's not something I plan to include in this project.

**Comment by kakins** [comment]
Perfect!  Thanks you guys... you just made my day a little better :)
