### ISSUE TITLE
Code snippets column width narrowed

### ISSUE THREAD

**Issue by DragonRulerX** [LanikSJ/slack-dark-mode#155]
Code snippets do not take up the full width of the screen.
In fact they take up a little less than half in width even if the code itself is wider - causing text wrapping.

**Comment by krazyito65** [comment]
Can you provide a screenshot please?

**Comment by jpool-cf** [comment]
Here is an example of the above issue. Also noticing that the background for code snippets is white instead of black, making things very hard to read :)

![image](https://user-images.githubusercontent.com/42589856/63449990-ee10e800-c3f5-11e9-9ee9-d75d08eac45c.png)

**Comment by krazyito65** [comment]
which is weird, becasue that seems to have happened recently, wasn't like that before, and i didn't do any updates =/

**Comment by jpool-cf** [comment]
Yeah, definitely wasn't the case last week :D

**Comment by LanikSJ** [comment]
I think the width depends on the type of snippet as I'm not able to reproduce this.

**Comment by krazyito65** [comment]
@DragonRulerX still need a screenshot about the width issue, and help us reproduce it
