### ISSUE TITLE
Light color persists on drop-down boxes

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#156]
**Describe the bug**
All drop-down boxes in the app are still in the light theme.

**To Reproduce**
1\. Go to 'Settings'
2\. Click on 'Language and Region'
3\. Open the drop-down box for the 'language selection'

**Expected behavior**
It should have a matching dark theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/63293641-25fd1b80-c28e-11e9-94cb-24be739547c9.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.0.1

**Additional context**
N/A

**Comment by vitorpiovezam** [comment]
I tried to apply css class to select tag or all inputs and no success :(. Maybe to fix this will need open developer tools to catch selector. See this [discussion](https://www.reddit.com/r/Slack/comments/955dro/how_do_i_open_the_chromium_developer_tools_in_the/)

**Comment by Zweih** [comment]
Found the selector: `div[role=listbox]`, though the order for the active list item properties has to be odd due to it Slack using React to manage to hover state rather than CSS directly.
