### ISSUE TITLE
White on white when hover over "X" to close thread in right sidebar

### ISSUE THREAD

**Issue by TyeMcQueen** [LanikSJ/slack-dark-mode#159]
**Describe the bug**
Hovering over the "X" to close a thread in the right sidebar highlights it producing a white "X" in a white box.

**To Reproduce**
1\. Find a channel that has a thread
2\. Click on the thread to open it in the right sidebar
3\. Hover your mouse over the "X" that closes the thread.
4\. Notice the bright white box and that you can no longer see the "X".

**Expected behavior**
The highlight box should be a more "dark" color.

**Screenshots**
<img width="354" alt="WhiteThreadCloseDarkTheme" src="https://user-images.githubusercontent.com/41888/63371552-1850a000-c339-11e9-94e1-8ed779b78acd.png">

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version 4.0.2

**Additional context**

**Comment by mikepenz** [comment]
Can not reproduce this on Mac with version 4.0.2 of slack and the latest state of this project

![image](https://user-images.githubusercontent.com/1476232/63530965-d0cc3e80-c507-11e9-94aa-99994c23bb65.png)

**Comment by krazyito65** [comment]
Miike, make sure you turn off your custom CSS when you test the issues.

**Comment by mikepenz** [comment]
Also not happening without the custom colors

**Comment by krazyito65** [comment]
Yea... I just upgraded to 4.0.2 so now it doesn't happen.

**Comment by LanikSJ** [comment]
I used to get the white box too and now it's gone already.  So I think we're good.
