### ISSUE TITLE
White theme code/text snippet

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#162]
**Describe the bug**
Code and text snippets are not having a dark theme applied.

**To Reproduce**
1\. Go to attach a text or code snippet.
2\. Observe the wrong theme.

**Expected behavior**
It should be dark.

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/63465206-5c6d9e80-c426-11e9-966f-0ffd384cd354.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.0.1

**Additional context**
N/A

**Comment by LanikSJ** [comment]
I saw this first in #155 but yes it's a bug.

**Comment by robmonte** [comment]
My bad, didn't mean to duplicate.

**Comment by LanikSJ** [comment]
You didn't #155 deals with a size of the same text box. 🙂

**Comment by TyeMcQueen** [comment]
Just FYI, I don't have this problem on 4.0.2

<img width="680" alt="DarkSnippet" src="https://user-images.githubusercontent.com/41888/63488611-71692280-c464-11e9-8410-405695d832e8.png">

**Comment by omahonyb** [comment]
Still occurring for me. Also, when you click on a user, the whole pop up is white.

**Comment by ycchen24** [comment]
> Just FYI, I don't have this problem on 4.0.2
> 
> <img alt="DarkSnippet" width="680" src="https://user-images.githubusercontent.com/41888/63488611-71692280-c464-11e9-8410-405695d832e8.png">

i believe the bug occurs after you created snippets, and the background of preview snippets on channel is white. not the pop up page

**Comment by nathan-fiscaletti** [comment]
Funny that someone made this only 19 hours ago. I've been experiencing it since i started using slack-dark-mode, and just this morning thought I would go open an issue for it, only to find out someone beat me to it by 19 hours 😐

**Comment by nathan-fiscaletti** [comment]
Also, just to mention, this is still happening in 4.0.2.

**Comment by mikepenz** [comment]
For me it also seems to work... I am on Mac with version 4.0.2
![image](https://user-images.githubusercontent.com/1476232/63530888-a5495400-c507-11e9-8d60-5fa6a5752514.png)

**Comment by krazyito65** [comment]
> For me it also seems to work... I am on Mac with version 4.0.2
> ![image](https://user-images.githubusercontent.com/1476232/63530888-a5495400-c507-11e9-8d60-5fa6a5752514.png)

Pretty sure this is not the issue. Look at the first post, it deals with snippets posted within a channel

![image](https://user-images.githubusercontent.com/479738/63530998-351ddc80-c4cd-11e9-9543-4968ded445d2.png)

**Comment by mikepenz** [comment]
@krazyito65 oh you are right. I see now

**Comment by mikepenz** [comment]
Will open a PR with the fix soon
