### ISSUE TITLE
Look for way to get nvm node installs to work properly with our scripts

### ISSUE THREAD

**Issue by krazyito65** [LanikSJ/slack-dark-mode#190]
**Is your feature request related to a problem? Please describe.**
When NVM is used to install node, find a way to export paths to install dark mode properly.

**Comment by croax** [comment]
I have the following issues:

`sudo ./slack-dark-mode.sh

This script requires sudo privileges.
You'll need to provide your password.
npx is /usr/local/bin/npx

Adding Dark Theme Code to Slack...
cp: dark-theme.css: No such file or directory
npx: installed 21 in 1.301s
./slack-dark-mode.sh: line 71: event-listener.js: No such file or directory
npx: installed 21 in 1.3s

Done! After executing this script restart Slack for changes to take effect.`

Fixing dark-theme.css:

`wget https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css
mv black.css dark-theme.css`

Line 71:
`# Add JS Code to Slack
    sudo tee -a "$SLACK_FILEPATH" < $SLACK_EVENT_LISTENER`

**Comment by croax** [comment]
```
echo $SLACK_FILEPATH
/Applications/Slack.app/Contents/Resources/app.asar.unpacked/dist/ssb-interop.bundle.js
echo $SLACK_EVENT_LISTENER
event-listener.js
```

**Comment by croax** [comment]
I assume it's more effective to actually clone the git repo first and then go on with executing scripts - it works like a charm ;)

**Comment by dhruvasagar** [comment]
@krazyito65 This isn't an nvm issue however, the issue is that the script expects 2 things : 

* dark-theme.css in the Slack Resources directory
* event-listener.js in the current directory where you execute the script

if you clone the repo, the both these are satisfied, however if you want to avoid cloning, then you'll have to download both these files from this repo and then try to execute the script again ensuring the above two conditions are satisfied.

**Comment by krazyito65** [comment]
That's not what I observed.  The issue I had with nvm (on Ubuntu) was that any root commands could not find the node/npm/npx binaries to use since they were only local to my user.  Basically i need to find a way to export my user's PATH to root.

I haven't had a chance to do more testing for this which I hope to do next week.

**Comment by dhruvasagar** [comment]
@krazyito65 I guess my comments were with regards to comments by @croax .

@krazyito65 regarding sudo npx issue, maybe this would help - https://stackoverflow.com/questions/21215059/cant-use-nvm-from-root-or-sudo

**Comment by dhruvasagar** [comment]
@krazyito65 in either case I wouldn't consider this to be an issue with slack-dark-mode itself, it's more of a configuration / setup issue which IMO is outside it's realm of influence and it should not try to work around it.

**Comment by krazyito65** [comment]
I helped create some of the linux scripts here, and I wrote this for myself to remind me to try to fiddle with the script settings to try to get it to work with nvm.  I want to get it to work for many other configurations, because it was a pain for me to have to uninstall nvm and reinstall a base version of node just to get this script to work.

Would like to be able to fix that for other people.

**Comment by krazyito65** [comment]
@LanikSJ this actually happens on linux
