### ISSUE TITLE
Channel topic background is white on hover

### ISSUE THREAD

**Issue by azhsetiawan** [LanikSJ/slack-dark-mode#203]
**Describe the bug**
Channel topic background is white on hover

**To Reproduce**
1\. Go to any channel 
2\. Channel details
3\. Hover on channel topic

**Expected behavior**
Background should be black and text white

**Screenshots**
![image](https://user-images.githubusercontent.com/3045602/63992443-fc59b500-cb15-11e9-9075-6b1e480389ef.png)

**Desktop (please complete the following information):**
-   macOS Mojave 10.14.3
-   Slack 4.0.3

**Comment by azhsetiawan** [comment]
Would you add this to next update?
```
/* fix channel topic on hover */
.p-classic_nav__model__title__info__topic--focus-within .p-classic_nav__model__title__info__topic__text:before,
.p-classic_nav__model__title__info__topic:hover .p-classic_nav__model__title__info__topic__text:before {
  background: var(--main-dark-highlight);
}
```
thanks

**Comment by LanikSJ** [comment]
Thanks I'll put that in on the next update.
