### ISSUE TITLE
Slack audio call embedded info box not themed in DM's

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#207]
**Describe the bug**
Call info embedded into text chat isn't themed properly

**To Reproduce**
1\. Start a call or call another user
2\. Observe the embedded call information within the DM

**Expected behavior**
The box should be dark themed.

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/64200707-ad33bd00-ce52-11e9-9904-3fd13e766005.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.0.3

**Additional context**
N/A

**Comment by LanikSJ** [comment]
This was fixed in #183 have you updated your CSS since then?

cc: @Zweih

**Comment by Zweih** [comment]
I think this is a new separate issue, I didn't see this back when I made the PR. There may have been an update since then. I can make a quick fix and push a PR.

**Comment by LanikSJ** [comment]
Awesome thank you @Zweih
