### ISSUE TITLE
Breaks Slack v4.0.3

### ISSUE THREAD

**Issue by dhruvasagar** [LanikSJ/slack-dark-mode#215]
**Describe the bug**
The code that appends `event-listener.js` to `ssb-interop.bundle.js` broke slack since it had a comment for source maps on the last line without a new line. So the append results in malformed js that breaks slack. Tested with slack v4.0.3.

**To Reproduce**
1\. Install Slack Dark Mode
2\. Restart Slack (can see error on console with the help of `SLACK_DEVEOPER_MENU="true" open /Application/Slack.app`)
3\. App stays on loading screen.
4\. See error in console.

**Expected behavior**
Slack should open and load the dark theme.

**Desktop (please complete the following information):**
-   macOS Mojave v10.14.6
-   Slack Version v4.0.3

**Comment by LanikSJ** [comment]
Can you provide the screenshot or the errors you saw? Screenshot would be preferred or both would be even better.

**Comment by dhruvasagar** [comment]
Ok, i'll try to reproduce the issue again and post the screenshots

**Comment by LanikSJ** [comment]
I saw your PR and there's already an empty line in the beginning of `event-listener.js` so that shouldn't cause any breakage.

**Comment by dhruvasagar** [comment]
@LanikSJ interesting, looks like it was a goofup on my side then. i'll close the issue. Thanks.

**Comment by LanikSJ** [comment]
No problem at all, have a good day. 🙂
