### ISSUE TITLE
Workspace rules wrong text color in profile edit page

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#219]
**Describe the bug**
The workspace custom rules area is the wrong text color when editing your profile.

**To Reproduce**
1\. Go to 'Edit Profile' where you can change your display name, etc.
2\. See error

**Expected behavior**
The text color should be light as the background is dark.

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/64268558-effe9f00-cefd-11e9-8e6e-dcb78238ac83.png)

The above screenshot is how it looks. Here is me highlighting the text to better see the issue:
![image](https://user-images.githubusercontent.com/17119716/64268630-0c024080-cefe-11e9-86a0-b5c8ce8eed18.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.1.0

**Additional context**
Not all slack users have custom workspace rules in this profile edit screen.

**Comment by LanikSJ** [comment]
I sort of knew what we did in #218 would come to bite us cc: @dhruvasagar 

Should be a matter of putting the `color` element back in.

**Comment by dhruvasagar** [comment]
@LanikSJ what should the color be ?

**Comment by dhruvasagar** [comment]
@LanikSJ not sure if it's actually related to #218 though.

**Comment by LanikSJ** [comment]
`color: #f8f8f8` should do the trick here: https://github.com/LanikSJ/slack-dark-mode/pull/218/commits/f8619c504133b287f4c0afb0de25bf0b6c330fcf

Basically undoing what this commit did should fix the problem.  I have no way of testing it however.

**Comment by dhruvasagar** [comment]
@LanikSJ ok will look at it in the evening.

**Comment by LanikSJ** [comment]
@dhruvasagar I think you're right about this not being related.  In any case it should be fixed shortly as soon as testing passes.
