### ISSUE TITLE
Right Sidebar Missing Border

### ISSUE THREAD

**Issue by dhruvasagar** [LanikSJ/slack-dark-mode#220]
**Describe the bug**
Right sidebar is missing a border in dark mode.

**To Reproduce**
1\. Open a Thread / Keyboard Shortcuts
2\. See error

**Expected behavior**
Right sidebar should have a border for visual separation, looks better that way.

**Screenshots**
![Screen Shot 2019-09-04 at 10 56 14 AM](https://user-images.githubusercontent.com/88258/64269037-31e01300-cf07-11e9-9631-afc4dc89730e.png)

**Desktop (please complete the following information):**

-   macOS Mojave 10.14.6 (18G95)
-   Slack Version v4.0.3

**Comment by robmonte** [comment]
This same idea should be applied to the left sidebar as it is also missing a border separation.

**Comment by dhruvasagar** [comment]
@robmonte Thanks for pointing it out, I hadn't noticed. I'll fix that in a separate PR

**Comment by dhruvasagar** [comment]
Update: I have since pushed a fix for both sidebars in #221 , kindly have a look.
