### ISSUE TITLE
File attachment grid wrong background color

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#222]
**Describe the bug**
White background on file attachment grid when sharing a non-text file.

**To Reproduce**
1\. Go to a 'DM' or channel.
2\. Share one or more non-text files.

**Expected behavior**
The background color should be dark instead of white.

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/64287293-de7cbd80-cf24-11e9-812a-b58e8ae8000e.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.1

**Additional context**
To make this look correct, I suspect it may take a little more work than just changing the color.

The first problem is that If it is changed to the lighter gray background color, it will blend in with (and hide) the panel.
The second problem is that if it is changed to the darker color, it will match the file grid and hide those individual squares.

**Comment by LanikSJ** [comment]
@robmonte it's not perfect but that's the best I've been able to do:
![image](https://user-images.githubusercontent.com/12159404/64300519-ebec7480-cf31-11e9-85fc-cbec76c67b63.png)

**Comment by robmonte** [comment]
Looks good actually 👍
