### ISSUE TITLE
DM scroll bar not themed

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#223]
**Describe the bug**
The scroll bar in the Direct Message list isn't themed

**To Reproduce**
1\. Go to 'Direct Messages'
2\. See error

**Expected behavior**
The bar should be a darker grey instead of white

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/64289737-63b6a100-cf2a-11e9-8cf0-a66045a75cb0.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.1.0

**Additional context**
N/A

**Comment by LanikSJ** [comment]
I don't have this problem any more in the latest 4.1.0 beta2 in my DM windows.

**Comment by robmonte** [comment]
Uninstalled/reinstalled on macOS 4.1.0-beta3 and the issue is still present.

To link this with https://github.com/LanikSJ/slack-dark-mode/issues/224 It seems like most of the scroll bars are off, with the exception of the main left sidebar's scroll bar. The main sidebar looks good, currently like this:
![image](https://user-images.githubusercontent.com/17119716/64357927-281fe380-cfcb-11e9-9411-58e2635b441d.png)


Inside an actual channel, the scrollbar is a different color:
![image](https://user-images.githubusercontent.com/17119716/64357999-44238500-cfcb-11e9-9a25-15a445babc70.png)

When reading a thread, it looks more like the channel list scrollbar in the separate issue I opened:
![image](https://user-images.githubusercontent.com/17119716/64358135-7cc35e80-cfcb-11e9-8ed5-1f2ac523cfd5.png)


Perhaps I should close these 2 issues and reopen a new one under "Scrollbars are inconsistently themed?"
