### ISSUE TITLE
Windows - NPX fails with space in path.

### ISSUE THREAD

**Issue by krazyito65** [LanikSJ/slack-dark-mode#238]
While testing #204 npx was failing to package the asar correctly on windows when I had a space in my path.  I've since removed the space so i don't have an easy way to test at the moment.

**Comment by krazyito65** [comment]
@nlowe you think you could send me some resources to make a windows VM?  I think there's a built in way within windows to do it..

**Comment by nlowe** [comment]
I have docker installed so I have to use `Hyper-V` to manage containers. Pretty sure you need W10 Pro or Enterprise. [New versions of windows has ways to create a W10 Dev image from within hyper-v](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20170726-hyper-v-virtual-machine-gallery-and-networking-improvements). This downloads a machine image from microsoft. You can then create a new user with a space in their name to test this issue.

If you want to start from scratch, you can use the W10 media creation tools to make an ISO that you can attach to a VM and install windows that way.

**Comment by krazyito65** [comment]
I have hyper-v installed, I just never had much luck with docker/hyper-v.. I'll try to see if i can use the built in tool to create a new vm.

**Comment by krazyito65** [comment]
Can't make a VM because Hyper-V doens't let me change what disk to save to 🙃 

My main disk had like 25gb left, recommended is 32, tried to google how to change the drive and failed, decided to try it anyway, it fails and now i have 15 GB of space left and can't delete the VM 🙃

**Comment by krazyito65** [comment]
now im going through trying to clean up space... ill get there eventually..

**Comment by krazyito65** [comment]
Here's the errors: 
![image](https://user-images.githubusercontent.com/479738/64470472-15132d80-d109-11e9-9c90-ec4b43b28e19.png)

**Comment by krazyito65** [comment]
Well the fix is to do this:
`npm config set cache C:\tmp\nodejs\npm-cache --global`

But I'm unsure how to gracefully add that to the script without changing everyone's npm cache.
