### ISSUE TITLE
Slash Commands and Mention Scrollbars are White

### ISSUE THREAD

**Issue by LanikSJ** [LanikSJ/slack-dark-mode#242]
**Describe the bug**

**To Reproduce**
1\. Go to any channel or DM
2\. Type in `@` or `/` 

**Expected behavior**
The scrollbar should be themed with the rest of dark mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/12159404/64442883-89a48880-d085-11e9-9c5a-5765586cbc62.png)

**Desktop (please complete the following information):**

-   OS: macOS 10.15 Catalina
-   Slack Version 4.1.0-beta3

**Additional context**
I'm not sure how to find the elements which control sidebars.  I'm open to input / ideas.

**Comment by Zweih** [comment]
This appears to be a symptom of having `Show scroll bars` set to `Always` in the OS System Preferences -> General. It doesn't happen when I have it set to `Automatically based  on mouse or trackpad` or `When scrolling`. 

Here's what I normally see when set to `When scrolling`: 
<img width="338" alt="Screen Shot 2019-09-11 at 2 10 41 PM" src="https://user-images.githubusercontent.com/15152269/64723539-b51cde00-d49e-11e9-8741-f41bc1c3da98.png">

**Comment by LanikSJ** [comment]
Changing the Global pereference to anything other then `Automatically based on mouse or trackpad or When scrolling` seems to have the desired effect.  Likely why I can't seem to find any CSS elements.

**Comment by Zweih** [comment]
The best I can style it is like this, but it leaves a gap between the list items and the edge of the menu: 
<img width="548" alt="Screen Shot 2019-09-13 at 12 21 49 PM" src="https://user-images.githubusercontent.com/15152269/64883663-e7107a80-d62d-11e9-9b95-8503ab72c7b8.png">

**Comment by LanikSJ** [comment]
I'm okay with that actually.

**Comment by Zweih** [comment]
Another minor issue is that the scrollbar persists when scrollbar is on `Automatically based on mouse or trackpad` or `When scrolling`. I do have a work around for that but it requires more JS.

This is what I've been testing:
```
document.addEventListener('DOMContentLoaded', function() {
  const fs = require('fs');
  const filePath = "SLACK_DARK_THEME_PATH";
  const IS_DARK_KEY = "isDark";

  const scrollbar = `
  .c-texty_autocomplete__body::-webkit-scrollbar {
    background-color: var(--main-dark-highlight) !important;
    width: 10px !important;
  }

  .c-texty_autocomplete__body::-webkit-scrollbar-thumb {
    background-color: var(--main-bg-color) !important;
    border-radius: 5px !important;
  }`;

  const scrollStyleEl = document.createElement("style");
  scrollStyleEl.innerHTML = scrollbar;

  const addScrollBar = (head) => {
    const scrollDiv = document.createElement("div");
    scrollDiv.className = "scrollbar-measure";
    document.body.appendChild(scrollDiv);
    const scrollbarWidth = scrollDiv.offsetWidth - scrollDiv.clientWidth;
    document.body.removeChild(scrollDiv);

    if (scrollbarWidth === 15) {
      head.append(scrollStyleEl);
    };
  };

  fs.readFile(filePath, {
    encoding: 'utf-8'
  }, function(err, css) {
    if (!err) {
      const styleEl = document.createElement("style");
      const head = document.querySelector("head");
      styleEl.innerHTML = css;

      const applyDark = () => {
        head.append(styleEl);
        addScrollBar(head);
      };

      const removeDark = () => {
        head.removeChild(styleEl);
        head.removeChild(scrollStyleEl);
      }

      if (localStorage.getItem(IS_DARK_KEY) === null) {
        localStorage.setItem(IS_DARK_KEY, true);
        window.location.reload(true);
      }

      if (JSON.parse(localStorage.getItem(IS_DARK_KEY))) {
        applyDark();
      }

      document.addEventListener("keydown", event => {
        if (event.ctrlKey && event.keyCode === 76) {
          const isDark = JSON.parse(localStorage.getItem(IS_DARK_KEY));
          isDark ? removeDark() : applyDark();
          localStorage.setItem(IS_DARK_KEY, !isDark);
        }
      });
    }
  });
});
```

**Comment by Zweih** [comment]
Alternatively we could just leave it on always for all users.

**Comment by LanikSJ** [comment]
I'm okay with always on as long as it's styled.
