### ISSUE TITLE
Windows 10. Slack version "Production 4.0.2 64-bit" with enabled dark mode opens and closes repeatedly when lauched.

### ISSUE THREAD

**Issue by kumamonishe** [LanikSJ/slack-dark-mode#248]
There is no way to launch Slack with dark mode after the last update. It just starts and stops repeatedly. Reverting back do light mode does not resolves the issue, only full reinstall with deletion of slack folders in ~\appdata\local and  ~\appdata\roaming allows Slack to run again, and it goes back to cycling restarts again if the dark mode is enabled. :(

**Comment by LanikSJ** [comment]
#204
