### ISSUE TITLE
Not working with Slack Version 4.0.3 (App Store) .

### ISSUE THREAD

**Issue by Brejendra-Amex** [LanikSJ/slack-dark-mode#254]
With the latest update Version 4.0.3 (App Store) . I’m not able to make it dark again. Any advise ?

**Comment by LanikSJ** [comment]
Not really if that's all the information I have to go by. Please answer the questions in the template you erased.

**Comment by alex4108** [comment]
I had to tinker quite a bit to get the CSS to apply using 4.0.3 w/ Mac.

What finally seemed to give Slack the kick it needed:
```

killall Slack
sudo -i
rm -rf /Applications/Slack.app/Content/Resources/app.asar.unpacked
npx extract /Applications/Slack.app/Content/Resources/app.asar /Applications/Slack.app/Content/Resources/app.asar.unpacked
```
Now go execute the script, as root
