### ISSUE TITLE
Check for npx dependency

### ISSUE THREAD

**Issue by alex4108** [LanikSJ/slack-dark-mode#255]
**Describe the bug**
Upon installation, execution fails due to missing dependencies

**To Reproduce**
1\. Fresh install of MacOS Mojave 
2\. Install Homebrew, Git, Slack
3\. Execute installation as provided in README

**Expected behavior**
Execution should check for dependencies and attempt to install prior to execution.  Execution should not report success when commands fail.

**Desktop (please complete the following information):**

-   OS: MacOS
-   Slack 4.0.3

**Screenshots**

<img width="752" alt="Screen Shot 2019-09-10 at 12 34 48 AM" src="https://user-images.githubusercontent.com/7796475/64586824-1dff3b80-d363-11e9-8699-71590a27bb11.png">

**Comment by LanikSJ** [comment]
The dependency is already checked for however I see the script didn't exit. I'll fix that in the next update.

**Comment by krazyito65** [comment]
Also think automatic installation of the required dependencies are out of scope for this project.
