### ISSUE TITLE
Slack Dark Mode Natively

### ISSUE THREAD

**Issue by LanikSJ** [LanikSJ/slack-dark-mode#258]
As of this writing Slack has implemented Slack Dark Mode natively:

![image](https://user-images.githubusercontent.com/12159404/64798406-ccf47080-d537-11e9-9cd2-b2140b277098.png)

Announcement: https://slackhq.com/dark-mode-for-slack-desktop

I'm on Slack 4.1.0 beta5 and I can see this option today.  I imagine other versions should be similar.

This project can still live and you can still use anything here to customize Slack to your liking.

Thank you everyone who contributed and made this happen. 🎉😎 🎉

**Comment by Zweih** [comment]
I think it would be nice if we pivoted the project more towards general UI customization rather than specifically dark mode. Also with the JS hooks I've found ways we could add our own extensions to Slack, such as an in-app graphical color changer.

**Comment by LanikSJ** [comment]
I've been thinking about the same thing since we don't really need dark mode any longer since it's already native.  We could change this project to just style certain parts to your liking or provide some options etc.

**Comment by justin-dwyer** [comment]
Hey folks, last week a coworker and I cloned this repo to make a "Simple Slack" UI for a hackathon. Essentially it hides the side and top menus so channels and threads fill the whole window, and it makes gifs hidden except on hover. Things to make Slack less distracting. 😃 I noticed your comments above and thought you might like what this does. We didn't plan to work on our project much outside the hackathon, but maybe it could be adopted here? https://github.com/justin-dwyer/simple-slack

**Comment by LanikSJ** [comment]
You're welcome to contribute the CSS if you like and I'll make it part of the repo.  It's really up to the user which CSS they choose to go with.  You'll have to work on the Shell portion to allow the user to select which CSS they want to go with.

I think this project might just add up with collection of CSS that someone can choose from using a menu.

I'm open for suggestions, I'm just mulling things over at this point. 🙂

**Comment by rtgibbons** [comment]
Two cents as an outside observer. Taking the above simple slack and breaking it into individual components, then upon running the script either read in a config or ask for selection and place the CSS. Say I just with auto-hide gifs and only the top hidden. 

One of the things I miss most from this is the coloring of code blocks; even having a full syntax highlighter for code blocks and snippets would be cool; So it becomes more of a UI plugin system.

**Comment by berk-can** [comment]
Thank you contributors for this amazing repo enabled many developers use slack in dark mode before native support, now it is time to use native dark mode

**Comment by kobuki** [comment]
Cool. We had to wait, like, 5-6 years for this? Thanks for this solution anyway, it was the most convenient of the several available ones. BTW, it stopped working on Slack 4.1.1. When I was about to file a bug, I noticed this one.
