### ISSUE TITLE
Wrong code highlighting

### ISSUE THREAD

**Issue by jet8a** [LanikSJ/slack-dark-mode#71]
**Screenshots**
<img width="781" alt="Screenshot 2019-06-27 at 15 20 50" src="https://user-images.githubusercontent.com/14956407/60249501-2bbe2c80-98ef-11e9-9f77-3d6f8e6d273a.png">

**Comment by LanikSJ** [comment]
Are you talking about the code highlights inside the "Untitled" block?

**Comment by jet8a** [comment]
> Are you talking about the code highlights inside the "Untitled" block?

No, I'm talking about the wrong black to white gradient

**Comment by LanikSJ** [comment]
That's not part of the code block but a transition.  Sorry that stays.  Feel free to fork this project and customize to your liking.
