### ISSUE TITLE
Dark text on dark background for external link cards

### ISSUE THREAD

**Issue by patroza** [LanikSJ/slack-dark-mode#73]
**Describe the bug**
Dark on dark is hard to read

**To Reproduce**
1. copy a github link into the conversation
2. find that the text 'github' is too dark to read. (the icon is also not great to read)

**Expected behavior**
The text is properly readable

**Screenshots**
<img width="592" alt="Screenshot 2019-07-14 at 10 47 23" src="https://user-images.githubusercontent.com/42661/61181317-ff135000-a624-11e9-856c-b5c3f2e92f08.png">

**Desktop (please complete the following information):**

-   OS: MacOS 10.14.5

**Comment by LanikSJ** [comment]
What's the version of Slack I can't reproduce this with Slack 4.0.

**Comment by LanikSJ** [comment]
![image](https://user-images.githubusercontent.com/12159404/61187391-88c31d80-a625-11e9-8009-fb26d914a137.png)
This is what I'm seeing.

**Comment by patroza** [comment]
Strange, I have the same problem if I send a StackOverflow link?
Im on latest store version, 4.0

**Comment by LanikSJ** [comment]
![image](https://user-images.githubusercontent.com/12159404/61229744-8cb27680-a6dd-11e9-99d1-1dd379488880.png)
No problem there either for me.

**Comment by patroza** [comment]
@LanikSJ you fixed it somehow since I reported it.
I've checked out latest master branch and `./slack-dark-mode.sh -u` and it works now.
diff says:
```
+.c-message_attachment__author_name {
+  color: #f8f8f8;
+}
+
 .c-message_attachment__border {
   background-color: #545454;
 }
@@ -3918,6 +3922,19 @@ a.c-member_slug, .c-member_slug--link, .c-mrkdwn__subteam--link {
   background: #222;
 }

+.p-archives_banner {
+  background-color: #363636;
+}
+
+.p-archives_banner__data_range {
+  background-color: #222;
+  color: #f8f8f8;
+}
+
+.p-archives_banner__jump {
+  color: #f8f8f8;
```
