### ISSUE TITLE
Light text on light background for extension action buttons

### ISSUE THREAD

**Issue by patroza** [LanikSJ/slack-dark-mode#74]
**Describe the bug**
Extension actions have light background and text

**To Reproduce**
1. have an extension with actions post to a channel
2. find that the action buttons are light on light

**Expected behavior**
The text is dark or the button is dark instead.

**Screenshots**
<img width="480" alt="Screenshot 2019-07-14 at 12 46 21" src="https://user-images.githubusercontent.com/42661/61182567-9d0f1680-a635-11e9-883b-269ae758ca11.png">

**Desktop (please complete the following information):**

-   OS: MacOS 10.14.5

**Comment by LanikSJ** [comment]
I can't reproduce this since I'm assuming this is an app of sorts.  Please start Slack with:
```bash
export SLACK_DEVELOPER_MENU=true; open -a /Applications/Slack.app
```

Then inspect the element and post screenshots of the element in question.

**Comment by patroza** [comment]
Somehow fixed since latest pull, similar to https://github.com/LanikSJ/slack-dark-mode/issues/73
