### ISSUE TITLE
windows with channels to black

### ISSUE THREAD

**Issue by vtrokhymenko** [LanikSJ/slack-dark-mode#78]
hi 

in my mind, the window with channels pretty to do at black not on the silver

i tried to change to black at settings but i can't 

or maybe u know to do this?

**Comment by LanikSJ** [comment]
Care to elaborate? Screenshot?

**Comment by vtrokhymenko** [comment]
i would gladly, but your script didn't working after reboot slack

**Comment by LanikSJ** [comment]
Please run the script again.  Certain bugs have been fixed since then.

**Comment by vtrokhymenko** [comment]
fixed to apple error
i spoke about this color 
![image](https://user-images.githubusercontent.com/8581044/61594493-41282d00-abf5-11e9-85fb-0d90663c4b28.png)
can u change this aka silver color to black?

**Comment by LanikSJ** [comment]
Are you talking about the scroll bar? That will make it quite invisible.

**Comment by vtrokhymenko** [comment]
no
i talking about all window with channels list

**Comment by LanikSJ** [comment]
Okay got it I'll look into it.
