### ISSUE TITLE
Support for easy (realtime) swapping between light and dark

### ISSUE THREAD

**Issue by patroza** [LanikSJ/slack-dark-mode#79]
**Is your feature request related to a problem? Please describe.**
I came across this; http://osxdaily.com/2018/11/15/automatic-dark-mode-macos-schedule/ and think it may be nice to switch to light mode at day time, and dark mode at night time. However that's not so easy with this Slack hack.

**Describe the solution you'd like**
I would like to be able to easily switch between Light/Dark mode via some command

As for a trigger we could maybe watch a file, but the question is then how to load/unload the theme :)

**Comment by LanikSJ** [comment]
That would require some under the hood changes in Slack which are out of the scope of this project.  I like the idea though. 🙂
