### ISSUE TITLE
dark-theme is not applied

### ISSUE THREAD

**Issue by tnesavich** [LanikSJ/slack-dark-mode#80]

**Comment by tnesavich** [comment]
/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js is missing

**Comment by zoltaroth** [comment]
are you running slack 4.0?

**Comment by lacostenycoder** [comment]
@zoltaroth I am running Slack 4.0.0 and this file doesn't exist on my system, I'm on Mac 10.14.13
and Slack Version 4.0.0 (Production)

**Comment by Mackarous** [comment]
I am having similar issues. Was installing but now it doesn't work anymore

**Comment by gsaraf-carecloud** [comment]
`open -e ~/Library/Application\ Support/Slack/local-settings.json` and edit `bootSonic` to `never`, quite Slack, re-apply the script `./slack-dark-mode.sh -u` and start Slack.

**Comment by tnesavich** [comment]
@here

Wanted to share a couple more things to save people time that I tried just now to get this to work.

Test 1:
Uncommenting "//#sourceMappingURL=ssb-interop.bundle.js.map" in /Applications/Slack.app/Contents/Resources/app.asar.unpacked/dist/ssb-interop.bundle.js

Result 1:
Fail

Test 2:
Added the following to /Applications/Slack.app/Contents/Resources/app.asar.unpacked/dist/ssb-interop.bundle.js

  $("<style></style>").appendTo('head').html('#reply_container.upload_in_threads .inline_message_input_container {background: padding-box #545454}');
  $("<style></style>").appendTo('head').html('.p-channel_sidebar {background: #363636 !important}'); 
  $("<style></style>").appendTo('head').html('#client_body:not(.onboarding):not(.feature_global_nav_layout):before {background: inherit;}'); 
Result 2:
Fail

**Comment by GoldenChaos** [comment]
> `open -e ~/Library/Application\ Support/Slack/local-settings.json` and edit `bootSonic` to `never`, quit Slack, re-apply the script `./slack-dark-mode.sh -u` and start Slack.

This did it for me. Cheers!

**Comment by zoltaroth** [comment]
The file I mentioned might be specific to the AppStore installer.  Please try the same thing except in ~/Library/Application\ Support/Slack/local-settings.json

**Comment by zoltaroth** [comment]
@LanikSJ closed out the previous issue thread where we were discussing this exact issue.  I am not sure if he overlooked it or didn't think it was an issue but hopefully he will update the script to handle this change as well.

**Comment by tnesavich** [comment]
@zoltaroth 

Thanks for the fix here:
https://github.com/LanikSJ/slack-dark-mode/issues/80#issuecomment-511931694

Worked like a charm!  My eyes are MUCH happier now!

**Comment by tnesavich** [comment]
@zoltaroth

Thanks for the fix here:
#80 (comment)

Worked like a charm! My eyes are MUCH happier now!

**Comment by soleares** [comment]
@zoltaroth Thanks! I had the App store version and had both files. After updating `~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json` it worked.

**Comment by sturmenta** [comment]
https://github.com/LanikSJ/slack-dark-mode/issues/80#issuecomment-512000767 this work for me

thanks 🔥

**Comment by EricVS** [comment]
@zoltaroth's solution worked for me too, applied the change in that one file and ran ./slack-dark-mode.sh. Nice and dark again, I can take off my sunglasses now :-)
Thank you!

**Comment by BabaYaga76** [comment]
Extreme novice here, with a love for all things dark mode. I was having the issue of not being able to find /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js as well. Now I'm struggling to find ~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json please advise.

**Comment by zoltaroth** [comment]
> Extreme novice here, with a love for all things dark mode. I was having the issue of not being able to find /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js as well. Now I'm struggling to find ~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json please advise.

Did you try: ~/Library/Application\ Support/Slack/local-settings.json ?

**Comment by BabaYaga76** [comment]
No such file or directory. And my permission was denied for ~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json
the perks of a work computer.

**Comment by desilinguist** [comment]
The dark mode script worked for me after editing both files `~/Library/Application\ Support/Slack/local-settings.json` and `~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json`! Thanks!

**Comment by lacostenycoder** [comment]
> `open -e ~/Library/Application\ Support/Slack/local-settings.json` and edit `bootSonic` to `never`, quit Slack, re-apply the script `./slack-dark-mode.sh -u` and start Slack.

re-running shell script was not needed in my case, edit file and restart alone worked.

**Comment by LanikSJ** [comment]
I haven't overlooked it, I'm trying to think of a good clean way to handle this use case.  If someone has any ideas I'm all ears.

**Comment by lacostenycoder** [comment]
> I haven't overlooked it, I'm trying to think of a good clean way to handle this use case. If someone has any ideas I'm all ears.

Where do we seem to be "stuck" ? I'm happy to offer ideas.

**Comment by LanikSJ** [comment]
There are 2 different versions directly downloaded from Slack web site or App Store each one has different locations for their config files.  I guess I can do this with bunch of if statements.

**Comment by lacostenycoder** [comment]
> There are 2 different versions directly downloaded from Slack web site or App Store each one has different locations for their config files. I guess I can do this with bunch of if statements.

You can probably just use sed on both files right?

```
sed -i '' 's/once/never/g' <path/to/file1>
sed -i '' 's/once/never/g' <path/to/file2>
```

**Comment by LanikSJ** [comment]
You can test new changes in: https://github.com/LanikSJ/slack-dark-mode/blob/local-settings/slack-dark-mode.sh

**Comment by zoltaroth** [comment]
> No such file or directory. And my permission was denied for ~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json
> the perks of a work computer.

did you use sudo?

**Comment by Base29** [comment]
Hello guys ... followed your suggestions but it did not worked for me ... it seems like my ```Support/Slack/local-settings.json``` file does not have a ```bootSonic``` entry ... any suggestions ??

```{"lastKnownLocale":"en-US","rxLogging":false,"useHwAcceleration":true,"spellCheckerVersion":"V1","hasSavedStaleCookies":true}```

**Comment by lacostenycoder** [comment]
@Base29 did you make sure you have the latest version of this repo?  I think this was fixed just yesterday.  Also if you installed Slack from app store, you may not have this file.

**Comment by Base29** [comment]
@lacostenycoder ... just pulled few hours ago and I don't remember how I installed slack ... So what is the workaround here ?

**Comment by bric3** [comment]
@Base29 I had the same issue, maybe I _mis-ran_ the script. Anyway the settings file appears in two location 

https://github.com/LanikSJ/slack-dark-mode/blob/68467126a925fd6d73855521685a33c0bd128d54/slack-dark-mode.sh#L16-L17

I had to edit the first one, manually.

**Comment by Base29** [comment]
@bric3 ... I had it working i opened this file ```~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application\ Support/Slack/local-settings.json``` with sudo and the ```bootSonic``` entry was there and I changed it to "never" and re ran that script and it worked ... :)

**Comment by patroza** [comment]
ran into the same issue, now Slack's beautiful again ;-)

**Comment by trejder** [comment]
Perfect! Now, would be great to know how to achieve the same under Windows. Because:

- I don't have `local-settings.json` file anywhere within any Slack directory (and actually anywhere in my entire disk),
- I have 1491 `.json` files, but non of them contains `bootSonic` entry,
- searching for any file (not just `.json`) reveals that `bootSonic` entry is only withing some `.js` files and some `.asar` files,

In addition, I don't have any file matching `*settings*` pattern within my Slack directory, so I pretty much don't have an idea where Slack keeps local settings in Windows 10 edition.

**Comment by zoltaroth** [comment]
> Perfect! Now, would be great to know how to achieve the same under Windows. Because:
> 
> * I don't have `local-settings.json` file anywhere within any Slack directory (and actually anywhere in my entire disk),
> * I have 1491 `.json` files, but non of them contains `bootSonic` entry,
> * searching for any file (not just `.json`) reveals that `bootSonic` entry is only withing some `.js` files and some `.asar` files,
> 
> In addition, I don't have any file matching `*settings*` pattern within my Slack directory, so I pretty much don't have an idea where Slack keeps local settings in Windows 10 edition.

I just got this working under Windows the other day.  Steps I followed:

1) Manually unpack / modify / repack the asar file in Local/slack/app-4.0.0/resources

Next the Tricky part is updating local-settings.json:

2) Go to %APPDATA%\slack (this should put you  in AppData/Roaming/Slack
3) ADD the "bootSonic":"never" item into the json object (it was not there by default) 
4) Make the file READONLY (it kept getting overwritten :()
5) Darkmode \o/

**Comment by nlowe** [comment]
I wrote up a powershell script in a gist to automate this: https://gist.github.com/nlowe/9da39b1fe88edc607bc343c482afa65a. Just re-run the patch script after every update to re-apply the theme. You can point it at any custom theme by setting `-CSSUrl` to the URL that hosts the custom CSS you wish to apply.

**Comment by benny-jon** [comment]
Another tip in case someone is still blocked after following the fix steps here:  Make sure you have **node** installed. For Mac: (brew install node). Because the script uses **npx**.

**Comment by kschar** [comment]
Installed Brew and Node (from within Brew), edited bootSonic to never, and ran 'sudo ./slack-dark-mode.sh -u' and it runs to completion with no errors but when I open Slack it still has white conversations :(   Running Slack 4.0.1  Thanks for any pointers.
