### ISSUE TITLE
Abort script execution unless executing user has root/sudo privileges

### ISSUE THREAD

**Issue by nelsnelson** [LanikSJ/slack-dark-mode#81]
**Is your feature request related to a problem? Please describe.**

I think that the warning about root comes too late in the `slack-dark-mode.sh` script, and results in the attempt to modify protected files.  Under ideal conditions, this is harmless.  But I feel it is programmatically a best practice to include an automatic root check for a script that will require admin privileges in order to modify write-protected files, very early on in the program's execution.

**Describe the solution you'd like**
I'd like to check for root privileges early in the execution of the program, and abort execution if the executing user does not have root privileges.

**Describe alternatives you've considered**
An alternative would be to refuse to operate on a system-wide installation of Slack either in a MacOS or Linux environment, and instead insist that the Slack application be installed in the user home `$HOME/Applications` directory, instead.  This way, this theme installation script can be ran without requiring escalated/admin privileges.

**Comment by LanikSJ** [comment]
This will be addressed in #88
