### ISSUE TITLE
Support installation on Slack 3.4.3

### ISSUE THREAD

**Issue by nelsnelson** [LanikSJ/slack-dark-mode#83]
**Is your feature request related to a problem? Please describe.**

Currently, the only version of Slack available for download from https://slack.com/downloads/mac is version 3.4.2.  Some people have not yet been able to upgrade to version 4.0.0.  This version of the `slack-dark-mode.sh` theme installation script does not support previous versions.

**Describe the solution you'd like**

I would like to check for the installed version of the Slack application, and apply a programmatic decision branch for which installation procedure to use.

**Describe alternatives you've considered**

It is possible that Slack will not distribute 3.4.2 at all for very much longer.  Nevertheless, I think it is important to include backwards compatibility for those users who have been unable to upgrade for some reason.  For instance, some enterprises tightly control what software is used on their systems.  On the other hand, running this installation script on such systems may not work at all, since sudo/root privileges are required.

**Comment by LanikSJ** [comment]
Seeing as 4.0 is released on Slack web site and App Store I'm not going to invest too much time into this but if you want to you can use the pre 4.0 version: https://github.com/LanikSJ/slack-dark-mode/tree/466ff22d5b606b6d5b2edeff54f4cd7a3bafc39c
