### ISSUE TITLE
White background with white text on "All unreads" tab

### ISSUE THREAD

**Issue by nicoyuste** [LanikSJ/slack-dark-mode#84]
**Describe the bug**
When you open the "All unreads" tab, you cannot see the title of each conversation because it has a white background and a white title.

**To Reproduce**
1\. Go to 'All unreads' tab

**Expected behavior**
Background should also be dark so the text can be read.

**Screenshots**
<img width="685" alt="Captura de pantalla 2019-07-17 a las 16 18 41" src="https://user-images.githubusercontent.com/5048526/61383361-ce464b80-a8ae-11e9-82e7-5a797b5c8295.png">

**Desktop:**
-   OS: macOS Mojave
-   Slack Version 4.0.0

**Comment by LanikSJ** [comment]
I was able to reproduce this.  Now if I can only get developer tools working again I can fix it.

**Comment by LanikSJ** [comment]
This fix won't be perfect, but that's the best I can do for now.  I'll add more fixes as the time permits so keep checking back for updates.

**Comment by nicoyuste** [comment]
Thanks for fixing!
