### ISSUE TITLE
Doesn't work with App Store version v4.0.0

### ISSUE THREAD

**Issue by desilinguist** [LanikSJ/slack-dark-mode#85]
**Describe the bug**
Running `./slack-dark-mode.sh` does the usual stuff but there's no effect on the Slack window at all - it's still white.

**Desktop (please complete the following information):**

-   OS: macOS Mojave 10.14.5
-   Slack Version: v4.0.0 (from the App Store)

**Comment by zoltaroth** [comment]
See this thread here: https://github.com/LanikSJ/slack-dark-mode/issues/80 for a fix.

**Comment by desilinguist** [comment]
That worked, thanks!
