### ISSUE TITLE
Don't working with OSX 10.14.5

### ISSUE THREAD

**Issue by hoangtrucit** [LanikSJ/slack-dark-mode#90]
**Describe the bug**
I run script done and restart slack but it's not effective

-   OS: 10.14.5
-   Slack Version: 4.0.0

**Comment by LanikSJ** [comment]
Please see #80

**Comment by dairennlombard** [comment]
The fixes described in #80 do not work for me:
 - "bootSonic" is set to never
 - I did a Help > Troubleshooting > Reset App Data (the only "Reset" option I have)

Neither worked, whether or not I re-ran the script or restarted the app.
